name: test all

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      #          pip install pytest-cover
      - name: Run tests and collect coverage
        run: |
          pip install .
          python examples/example.py
          python examples/example_old.py
      #        pytest --cov .
#      - name: Upload coverage reports to Codecov with GitHub Action
#        uses: codecov/codecov-action@v3
